server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/consultorios?serverTimezone=UTC
    username: root
    password: alancito2002
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
